apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-controller
spec:
  containers:
  - name: n1
    image: linuxserver/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80