apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-1-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "2Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/mongo-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mongo-1-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mongodb-1-service
  labels:
    run: mongodb-1-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    defacementComponent: mongodb-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mongodb-1
  labels:
    env: test
    defacementComponent: mongodb-1
spec:
  replicas: 1
  selector:
    matchLabels:
      defacementComponent: mongodb-1
  template:
    metadata:
      labels:
        defacementComponent: mongodb-1
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: "app"
                 operator: In
                 values:
                 - mongo
             topologyKey: "kubernetes.io/hostname"
      containers:
        - image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
          name: mongodb-1
          resources:
            requests:
              ephemeral-storage: "1Gi"
              cpu: "500m"
              memory: "1Gi"
            limits:
              ephemeral-storage: "2Gi"
              cpu: "700m"
              memory: "2Gi"
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"