apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-10T07:56:28Z"
  generateName: nodeapp-mongodb-55d4df4d5f-
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.19
    pod-template-hash: 55d4df4d5f
  name: nodeapp-mongodb-55d4df4d5f-sprc9
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nodeapp-mongodb-55d4df4d5f
    uid: 10922336-f271-42cd-beab-ad5770666e1c
  resourceVersion: "195121"
  selfLink: /api/v1/namespaces/default/pods/nodeapp-mongodb-55d4df4d5f-sprc9
  uid: 32392e54-fbf4-4237-a604-f82509c85354
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: mongodb
              app.kubernetes.io/instance: nodeapp
              app.kubernetes.io/name: mongodb
          namespaces:
          - default
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: MONGODB_EXTRA_USERNAMES
      value: user
    - name: MONGODB_EXTRA_DATABASES
      value: test_db
    - name: MONGODB_EXTRA_PASSWORDS
      valueFrom:
        secretKeyRef:
          key: mongodb-passwords
          name: nodeapp-mongodb
    - name: MONGODB_ROOT_USER
      value: root
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: nodeapp-mongodb
    - name: ALLOW_EMPTY_PASSWORD
      value: "no"
    - name: MONGODB_SYSTEM_LOG_VERBOSITY
      value: "0"
    - name: MONGODB_DISABLE_SYSTEM_LOG
      value: "no"
    - name: MONGODB_DISABLE_JAVASCRIPT
      value: "no"
    - name: MONGODB_ENABLE_JOURNAL
      value: "yes"
    - name: MONGODB_PORT_NUMBER
      value: "27017"
    - name: MONGODB_ENABLE_IPV6
      value: "no"
    - name: MONGODB_ENABLE_DIRECTORY_PER_DB
      value: "no"
    image: docker.io/bitnami/mongodb:5.0.9-debian-10-r11
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bitnami/scripts/ping-mongodb.sh
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    name: mongodb
    ports:
    - containerPort: 27017
      name: mongodb
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bitnami/scripts/readiness-probe.sh
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/mongodb
      name: datadir
    - mountPath: /bitnami/scripts
      name: common-scripts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: nodeapp-mongodb-token-hgsk2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: nodeapp-mongodb
  serviceAccountName: nodeapp-mongodb
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 360
      name: nodeapp-mongodb-common-scripts
    name: common-scripts
  - name: datadir
    persistentVolumeClaim:
      claimName: nodeapp-mongodb
  - name: nodeapp-mongodb-token-hgsk2
    secret:
      defaultMode: 420
      secretName: nodeapp-mongodb-token-hgsk2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-06-10T07:56:28Z"
    message: '0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master:
      }, that the pod didn''t tolerate, 2 pod has unbound immediate PersistentVolumeClaims.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
